name: Update Readme
on:
    schedule:
      - cron: '0 0 * * 0'
jobs:
    update:
        name: Update Readme
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: run
          run: cargo run
          env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: commit
          run: |
            git config --local user.name "hugo_stars bot"
            git commit -m "Updated ranking" -a
        - name: push
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
